import type { SecurityDomain, SecurityCriterion, Tab, ExportFormat } from "./types";

export const TABS: Tab[] = [
  { id: "overview", label: "Overview", labelVi: "Tổng quan", icon: "📊" },
  { id: "assessment", label: "Assessment", labelVi: "Đánh giá", icon: "🔍" },
  { id: "compliance", label: "Compliance", labelVi: "Tuân thủ", icon: "✅" },
  { id: "threats", label: "Threats", labelVi: "Mối đe dọa", icon: "⚠️" },
  { id: "training", label: "Training", labelVi: "Đào tạo", icon: "🎓" },
  { id: "devices", label: "Devices", labelVi: "Thiết bị", icon: "💻" },
  { id: "notifications", label: "Notifications", labelVi: "Thông báo", icon: "🔔" },
  { id: "reports", label: "Reports", labelVi: "Báo cáo", icon: "📄" },
  { id: "compare", label: "Compare", labelVi: "So sánh", icon: "⚖️" },
  { id: "settings", label: "Settings", labelVi: "Cài đặt", icon: "⚙️" },
  { id: "help", label: "Help", labelVi: "Trợ giúp", icon: "❓" },
];

export const EXPORT_FORMATS: ExportFormat[] = [
  { format: "json", label: "JSON", icon: "📋" },
  { format: "csv", label: "CSV", icon: "📈" },
  { format: "excel", label: "Excel", icon: "📗" },
  { format: "txt", label: "Text", icon: "📝" },
  { format: "html", label: "HTML", icon: "🌐" },
  { format: "pdf", label: "PDF", icon: "📄" },
];

export const DOMAINS: SecurityDomain[] = [
  { id: "access-control", name: "Access Control", nameVi: "Kiểm soát truy cập", description: "Quản lý định danh, phân quyền và kiểm soát truy cập", criteriaCount: 18, icon: "🔐" },
  { id: "network-security", name: "Network Security", nameVi: "An ninh mạng", description: "Bảo mật hạ tầng mạng và truyền thông", criteriaCount: 15, icon: "🌐" },
  { id: "data-protection", name: "Data Protection", nameVi: "Bảo vệ dữ liệu", description: "Mã hóa, phân loại và bảo vệ dữ liệu", criteriaCount: 16, icon: "🛡️" },
  { id: "application-security", name: "Application Security", nameVi: "Bảo mật ứng dụng", description: "Bảo mật phát triển và triển khai ứng dụng", criteriaCount: 14, icon: "🖥️" },
  { id: "incident-management", name: "Incident Management", nameVi: "Quản lý sự cố", description: "Phát hiện, ứng phó và phục hồi sự cố", criteriaCount: 12, icon: "🚨" },
  { id: "physical-security", name: "Physical Security", nameVi: "An ninh vật lý", description: "Bảo mật vật lý và môi trường", criteriaCount: 10, icon: "🏗️" },
  { id: "hr-security", name: "HR Security", nameVi: "An ninh nhân sự", description: "Bảo mật liên quan đến nhân sự", criteriaCount: 9, icon: "👥" },
  { id: "asset-management", name: "Asset Management", nameVi: "Quản lý tài sản", description: "Phân loại và quản lý tài sản thông tin", criteriaCount: 11, icon: "📦" },
  { id: "business-continuity", name: "Business Continuity", nameVi: "Kinh doanh liên tục", description: "Kế hoạch duy trì hoạt động kinh doanh", criteriaCount: 10, icon: "🔄" },
  { id: "compliance-legal", name: "Compliance & Legal", nameVi: "Tuân thủ & Pháp lý", description: "Đáp ứng quy định và yêu cầu pháp lý", criteriaCount: 12, icon: "⚖️" },
  { id: "cloud-security", name: "Cloud Security", nameVi: "Bảo mật đám mây", description: "Bảo mật dịch vụ và hạ tầng đám mây", criteriaCount: 13, icon: "☁️" },
  { id: "mobile-security", name: "Mobile Security", nameVi: "Bảo mật di động", description: "Bảo mật thiết bị và ứng dụng di động", criteriaCount: 9, icon: "📱" },
  { id: "iot-security", name: "IoT Security", nameVi: "Bảo mật IoT", description: "Bảo mật thiết bị Internet of Things", criteriaCount: 8, icon: "🔗" },
  { id: "crypto-management", name: "Cryptographic Management", nameVi: "Quản lý mã hóa", description: "Quản lý khóa và thuật toán mã hóa", criteriaCount: 11, icon: "🔑" },
  { id: "vendor-security", name: "Vendor Security", nameVi: "Bảo mật nhà cung cấp", description: "Đánh giá và quản lý rủi ro bên thứ ba", criteriaCount: 10, icon: "🏢" },
  { id: "monitoring-audit", name: "Monitoring & Audit", nameVi: "Giám sát & Kiểm toán", description: "Ghi log, giám sát và kiểm toán an ninh", criteriaCount: 12, icon: "📡" },
  { id: "security-governance", name: "Security Governance", nameVi: "Quản trị bảo mật", description: "Chiến lược, chính sách và quản trị bảo mật", criteriaCount: 13, icon: "🏛️" },
];

function generateCriteria(): SecurityCriterion[] {
  const criteria: SecurityCriterion[] = [];
  const riskLevels: Array<"critical" | "high" | "medium" | "low" | "info"> = ["critical", "high", "medium", "low", "info"];
  const isoControls = ["A.5.1", "A.5.2", "A.6.1", "A.6.2", "A.7.1", "A.7.2", "A.8.1", "A.8.2", "A.9.1", "A.9.2", "A.10.1", "A.11.1", "A.12.1", "A.13.1", "A.14.1"];
  const soc2Criteria = ["CC1.1", "CC1.2", "CC2.1", "CC3.1", "CC4.1", "CC5.1", "CC6.1", "CC7.1", "CC8.1", "CC9.1", "A1.1", "C1.1", "P1.1"];

  const domainCriteria: Record<string, Array<{ name: string; nameVi: string; desc: string; risk: "critical" | "high" | "medium" | "low" | "info" }>> = {
    "access-control": [
      { name: "Multi-Factor Authentication", nameVi: "Xác thực đa yếu tố", desc: "Yêu cầu MFA cho tất cả tài khoản", risk: "critical" },
      { name: "Password Policy Enforcement", nameVi: "Thực thi chính sách mật khẩu", desc: "Độ dài tối thiểu 12 ký tự, phức tạp", risk: "high" },
      { name: "Privileged Access Management", nameVi: "Quản lý truy cập đặc quyền", desc: "Kiểm soát tài khoản admin và quyền đặc biệt", risk: "critical" },
      { name: "Role-Based Access Control", nameVi: "Kiểm soát truy cập theo vai trò", desc: "Phân quyền dựa trên vai trò công việc", risk: "high" },
      { name: "Account Lockout Policy", nameVi: "Chính sách khóa tài khoản", desc: "Khóa sau 5 lần đăng nhập sai", risk: "medium" },
      { name: "Session Management", nameVi: "Quản lý phiên", desc: "Timeout phiên và kiểm soát phiên đăng nhập", risk: "high" },
      { name: "Single Sign-On Security", nameVi: "Bảo mật SSO", desc: "Triển khai SSO an toàn với SAML/OIDC", risk: "medium" },
      { name: "Service Account Management", nameVi: "Quản lý tài khoản dịch vụ", desc: "Kiểm soát tài khoản dịch vụ hệ thống", risk: "high" },
      { name: "Access Review Process", nameVi: "Quy trình rà soát truy cập", desc: "Rà soát quyền truy cập định kỳ hàng quý", risk: "medium" },
      { name: "Least Privilege Principle", nameVi: "Nguyên tắc đặc quyền tối thiểu", desc: "Chỉ cấp quyền cần thiết cho công việc", risk: "high" },
      { name: "Remote Access Security", nameVi: "Bảo mật truy cập từ xa", desc: "VPN và xác thực cho truy cập từ xa", risk: "critical" },
      { name: "API Authentication", nameVi: "Xác thực API", desc: "OAuth2/JWT cho tất cả API endpoints", risk: "high" },
      { name: "Directory Services Security", nameVi: "Bảo mật dịch vụ thư mục", desc: "Bảo mật LDAP/Active Directory", risk: "high" },
      { name: "Biometric Authentication", nameVi: "Xác thực sinh trắc học", desc: "Triển khai xác thực vân mặt/vân tay", risk: "medium" },
      { name: "Token Management", nameVi: "Quản lý token", desc: "Quản lý vòng đời và thu hồi token", risk: "high" },
      { name: "Emergency Access Procedures", nameVi: "Quy trình truy cập khẩn cấp", desc: "Break-glass procedures cho tình huống khẩn cấp", risk: "medium" },
      { name: "Federated Identity Management", nameVi: "Quản lý định danh liên kết", desc: "Liên kết định danh qua nhiều hệ thống", risk: "medium" },
      { name: "Access De-provisioning", nameVi: "Thu hồi truy cập", desc: "Tự động thu quyền khi nhân sự nghỉ việc", risk: "high" },
    ],
    "network-security": [
      { name: "Firewall Configuration", nameVi: "Cấu hình tường lửa", desc: "Tường lửa biên và nội bộ được cấu hình đúng", risk: "critical" },
      { name: "Network Segmentation", nameVi: "Phân đoạn mạng", desc: "Phân tách mạng thành các vùng bảo mật", risk: "high" },
      { name: "Intrusion Detection System", nameVi: "Hệ thống phát hiện xâm nhập", desc: "IDS/IPS triển khai trên toàn mạng", risk: "high" },
      { name: "DDoS Protection", nameVi: "Bảo vệ DDoS", desc: "Giải pháp chống tấn công từ chối dịch vụ", risk: "high" },
      { name: "Wireless Network Security", nameVi: "Bảo mật mạng không dây", desc: "WPA3 Enterprise cho WiFi doanh nghiệp", risk: "high" },
      { name: "DNS Security", nameVi: "Bảo mật DNS", desc: "DNSSEC và DNS filtering", risk: "medium" },
      { name: "VPN Infrastructure", nameVi: "Hạ tầng VPN", desc: "VPN site-to-site và remote access", risk: "high" },
      { name: "Network Traffic Analysis", nameVi: "Phân tích lưu lượng mạng", desc: "Giám sát và phân tích traffic bất thường", risk: "medium" },
      { name: "Port Management", nameVi: "Quản lý cổng", desc: "Đóng cổng không sử dụng và kiểm soát port", risk: "medium" },
      { name: "SSL/TLS Configuration", nameVi: "Cấu hình SSL/TLS", desc: "TLS 1.2+ cho tất cả kết nối", risk: "critical" },
      { name: "Network Access Control", nameVi: "Kiểm soát truy cập mạng", desc: "NAC kiểm soát thiết bị kết nối mạng", risk: "high" },
      { name: "Email Security Gateway", nameVi: "Cổng bảo mật email", desc: "Bảo vệ chống spam, phishing, malware qua email", risk: "high" },
      { name: "Web Application Firewall", nameVi: "Tường lửa ứng dụng web", desc: "WAF bảo vệ ứng dụng web", risk: "high" },
      { name: "Load Balancer Security", nameVi: "Bảo mật cân bằng tải", desc: "Bảo mật thiết bị cân bằng tải", risk: "medium" },
      { name: "Network Monitoring", nameVi: "Giám sát mạng", desc: "Giám sát mạng 24/7 với cảnh báo tự động", risk: "high" },
    ],
    "data-protection": [
      { name: "Data Encryption at Rest", nameVi: "Mã hóa dữ liệu lưu trữ", desc: "AES-256 cho dữ liệu nhạy cảm", risk: "critical" },
      { name: "Data Encryption in Transit", nameVi: "Mã hóa dữ liệu truyền tải", desc: "TLS cho tất cả dữ liệu truyền đi", risk: "critical" },
      { name: "Data Classification", nameVi: "Phân loại dữ liệu", desc: "Phân loại dữ liệu theo mức độ nhạy cảm", risk: "high" },
      { name: "Data Loss Prevention", nameVi: "Ngăn chặn mất mát dữ liệu", desc: "DLP kiểm soát dữ liệu ra khỏi tổ chức", risk: "high" },
      { name: "Backup Encryption", nameVi: "Mã hóa bản sao lưu", desc: "Mã hóa tất cả dữ liệu backup", risk: "high" },
      { name: "Data Retention Policy", nameVi: "Chính sách lưu giữ dữ liệu", desc: "Quy định thời gian lưu giữ và hủy dữ liệu", risk: "medium" },
      { name: "Database Security", nameVi: "Bảo mật cơ sở dữ liệu", desc: "Bảo mật và hardening cơ sở dữ liệu", risk: "high" },
      { name: "Personal Data Protection", nameVi: "Bảo vệ dữ liệu cá nhân", desc: "Tuân thủ GDPR/Nghị định 13 về DTTN", risk: "critical" },
      { name: "Data Masking", nameVi: "Che giấu dữ liệu", desc: "Ẩn dữ liệu nhạy cảm trong môi trường test", risk: "medium" },
      { name: "Secure Data Disposal", nameVi: "Tiêu hủy dữ liệu an toàn", desc: "Xóa vĩnh viễn dữ liệu không còn sử dụng", risk: "high" },
      { name: "Data Integrity Verification", nameVi: "Xác minh toàn vẹn dữ liệu", desc: "Kiểm tra hash và chữ ký số", risk: "high" },
      { name: "Cross-border Data Transfer", nameVi: "Chuyển dữ liệu xuyên biên giới", desc: "Tuân thủ quy định chuyển dữ liệu quốc tế", risk: "high" },
      { name: "Data Access Logging", nameVi: "Ghi log truy cập dữ liệu", desc: "Ghi lại mọi truy cập dữ liệu nhạy cảm", risk: "medium" },
      { name: "Encryption Key Management", nameVi: "Quản lý khóa mã hóa", desc: "Vòng đời và bảo mật khóa mã hóa", risk: "critical" },
      { name: "Tokenization", nameVi: "Token hóa", desc: "Thay thế dữ liệu nhạy cảm bằng token", risk: "medium" },
      { name: "Data Sovereignty", nameVi: "Quyền sở hữu dữ liệu", desc: "Đảm bảo dữ liệu lưu trữ trong phạm vi cho phép", risk: "high" },
    ],
    "application-security": [
      { name: "Secure Development Lifecycle", nameVi: "Vòng đời phát triển an toàn", desc: "Tích hợp bảo mật vào SDLC", risk: "high" },
      { name: "Static Code Analysis", nameVi: "Phân tích mã tĩnh", desc: "SAST trong pipeline CI/CD", risk: "high" },
      { name: "Dynamic Application Testing", nameVi: "Kiểm tra ứng dụng động", desc: "DAST cho ứng dụng đang chạy", risk: "high" },
      { name: "Input Validation", nameVi: "Xác thực đầu vào", desc: "Kiểm tra và làm sạch tất cả đầu vào", risk: "critical" },
      { name: "SQL Injection Prevention", nameVi: "Ngăn chặn SQL Injection", desc: "Sử dụng prepared statements và ORM", risk: "critical" },
      { name: "XSS Prevention", nameVi: "Ngăn chặn XSS", desc: "Encoding output và CSP headers", risk: "high" },
      { name: "API Security Testing", nameVi: "Kiểm tra bảo mật API", desc: "Test API với OWASP API Security Top 10", risk: "high" },
      { name: "Container Security", nameVi: "Bảo mật container", desc: "Quét lỗ hổng image và runtime security", risk: "high" },
      { name: "Dependency Scanning", nameVi: "Quét thư viện", desc: "Kiểm tra lỗ hổng trong thư viện bên thứ ba", risk: "high" },
      { name: "Code Review Process", nameVi: "Quy trình review mã", desc: "Bắt buộc review mã trước khi merge", risk: "medium" },
      { name: "Secret Management in Code", nameVi: "Quản lý bí mật trong mã", desc: "Không hardcode secrets trong source code", risk: "critical" },
      { name: "Application Logging", nameVi: "Ghi log ứng dụng", desc: "Ghi log bảo mật cho tất cả ứng dụng", risk: "medium" },
      { name: "Error Handling Security", nameVi: "Bảo mật xử lý lỗi", desc: "Không để lộ thông tin qua thông báo lỗi", risk: "medium" },
      { name: "Secure Configuration", nameVi: "Cấu hình an toàn", desc: "Hardening cấu hình ứng dụng và server", risk: "high" },
    ],
    "incident-management": [
      { name: "Incident Response Plan", nameVi: "Kế hoạch ứng phó sự cố", desc: "Tài liệu hóa quy trình ứng phó sự cố", risk: "critical" },
      { name: "Incident Detection", nameVi: "Phát hiện sự cố", desc: "Hệ thống phát hiện sự cố tự động", risk: "high" },
      { name: "Incident Classification", nameVi: "Phân loại sự cố", desc: "Phân loại mức độ nghiêm trọng sự cố", risk: "medium" },
      { name: "Incident Response Team", nameVi: "Đội ứng phó sự cố", desc: "CSIRT với vai trò và trách nhiệm rõ ràng", risk: "high" },
      { name: "Incident Communication", nameVi: "Truyền thông sự cố", desc: "Quy trình thông báo sự cố nội bộ và bên ngoài", risk: "medium" },
      { name: "Forensic Investigation", nameVi: "Điều tra pháp y số", desc: "Năng lực điều tra và thu thập bằng chứng số", risk: "high" },
      { name: "Incident Recovery", nameVi: "Phục hồi sự cố", desc: "Quy trình khôi phục hệ thống sau sự cố", risk: "high" },
      { name: "Post-Incident Review", nameVi: "Rà soát sau sự cố", desc: "Phân tích nguyên nhân gốc rễ và bài học", risk: "medium" },
      { name: "Incident Documentation", nameVi: "Tài liệu hóa sự cố", desc: "Ghi chép đầy đủ chi tiết sự cố", risk: "medium" },
      { name: "Breach Notification", nameVi: "Thông báo vi phạm", desc: "Thông báo vi phạm dữ liệu theo quy định", risk: "high" },
      { name: "Incident Simulation", nameVi: "Mô phỏng sự cố", desc: "Diễn tập ứng phó sự cố định kỳ", risk: "medium" },
      { name: "Threat Intelligence", nameVi: "Tình báo mối đe dọa", desc: "Thu thập và chia sẻ thông tin mối đe dọa", risk: "high" },
    ],
    "physical-security": [
      { name: "Data Center Physical Security", nameVi: "An ninh vật lý trung tâm dữ liệu", desc: "Kiểm soát truy cập vật lý vào DC", risk: "critical" },
      { name: "CCTV Surveillance", nameVi: "Camera giám sát", desc: "Hệ thống camera giám sát 24/7", risk: "high" },
      { name: "Access Badge System", nameVi: "Hệ thống thẻ ra vào", desc: "Thẻ thông minh kiểm soát ra vào", risk: "high" },
      { name: "Visitor Management", nameVi: "Quản lý khách thăm", desc: "Đăng ký và giám sát khách thăm", risk: "medium" },
      { name: "Environmental Controls", nameVi: "Kiểm soát môi trường", desc: "Điều hòa, phòng cháy chữa cháy, UPS", risk: "high" },
      { name: "Secure Disposal of Media", nameVi: "Tiêu hủy phương tiện an toàn", desc: "Xử lý an toàn ổ cứng, tài liệu", risk: "high" },
      { name: "Clean Desk Policy", nameVi: "Chính sách bàn làm việc sạch", desc: "Không để tài liệu nhạy cảm trên bàn", risk: "low" },
      { name: "Server Room Security", nameVi: "An ninh phòng máy chủ", desc: "Kiểm soát truy cập phòng server", risk: "critical" },
      { name: "Perimeter Security", nameVi: "An ninh chu vi", desc: "Hàng rào, cổng, bảo vệ canh gác", risk: "medium" },
      { name: "Power Redundancy", nameVi: "Dự phòng nguồn điện", desc: "UPS và máy phát điện dự phòng", risk: "high" },
    ],
    "hr-security": [
      { name: "Background Screening", nameVi: "Rà soát lý lịch", desc: "Kiểm tra lý lịch nhân viên trước khi tuyển", risk: "high" },
      { name: "Security Awareness Training", nameVi: "Đào tạo nhận thức bảo mật", desc: "Huấn luyện bảo mật cho tất cả nhân viên", risk: "high" },
      { name: "Confidentiality Agreements", nameVi: "Thỏa thuận bảo mật", desc: "Ký NDA với nhân viên và nhà thầu", risk: "medium" },
      { name: "Acceptable Use Policy", nameVi: "Chính sách sử dụng chấp nhận được", desc: "Quy định sử dụng tài nguyên IT", risk: "medium" },
      { name: "Disciplinary Process", nameVi: "Quy trình kỷ luật", desc: "Xử lý vi phạm chính sách bảo mật", risk: "medium" },
      { name: "Exit Procedures", nameVi: "Quy trình nghỉ việc", desc: "Thu hồi truy cập khi nhân viên nghỉ", risk: "high" },
      { name: "Role Change Procedures", nameVi: "Quy trình thay đổi vai trò", desc: "Điều chỉnh quyền truy cập khi thay đổi vị trí", risk: "medium" },
      { name: "Security Culture", nameVi: "Văn hóa bảo mật", desc: "Xây dựng văn hóa bảo mật trong tổ chức", risk: "medium" },
      { name: "Phishing Simulation", nameVi: "Mô phỏng phishing", desc: "Kiểm tra nhân viên với email giả mạo", risk: "high" },
    ],
    "asset-management": [
      { name: "Asset Inventory", nameVi: "Danh mục tài sản", desc: "Danh sách đầy đủ tất cả tài sản IT", risk: "high" },
      { name: "Asset Classification", nameVi: "Phân loại tài sản", desc: "Phân loại tài sản theo mức độ quan trọng", risk: "medium" },
      { name: "Asset Ownership", nameVi: "Quyền sở hữu tài sản", desc: "Xác định chủ sở hữu cho mỗi tài sản", risk: "medium" },
      { name: "Software License Management", nameVi: "Quản lý giấy phép phần mềm", desc: "Theo dõi và tuân thủ giấy phép", risk: "medium" },
      { name: "Hardware Lifecycle", nameVi: "Vòng đời phần cứng", desc: "Quản lý từ mua sắm đến tiêu hủy", risk: "low" },
      { name: "Configuration Management", nameVi: "Quản lý cấu hình", desc: "Baseline cấu hình cho tất cả hệ thống", risk: "high" },
      { name: "Change Management", nameVi: "Quản lý thay đổi", desc: "Quy trình phê duyệt thay đổi hệ thống", risk: "high" },
      { name: "Shadow IT Detection", nameVi: "Phát hiện Shadow IT", desc: "Phát hiện phần mềm/dịch vụ không được phép", risk: "medium" },
      { name: "Media Handling", nameVi: "Xử lý phương tiện", desc: "Quản lý USB, ổ cứng di động", risk: "medium" },
      { name: "Asset Tracking", nameVi: "Theo dõi tài sản", desc: "GPS/RFID theo dõi tài sản di động", risk: "low" },
      { name: "End-of-Life Management", nameVi: "Quản lý hết vòng đời", desc: "Kế hoạch thay thế hệ thống cũ", risk: "medium" },
    ],
    "business-continuity": [
      { name: "Business Impact Analysis", nameVi: "Phân tích tác động kinh doanh", desc: "Xác định hệ thống quan trọng và RTO/RPO", risk: "critical" },
      { name: "Disaster Recovery Plan", nameVi: "Kế hoạch phục hồi thảm họa", desc: "DRP cho tất cả hệ thống quan trọng", risk: "critical" },
      { name: "Backup Strategy", nameVi: "Chiến lược sao lưu", desc: "Sao lưu 3-2-1 với kiểm tra định kỳ", risk: "high" },
      { name: "Recovery Testing", nameVi: "Kiểm tra phục hồi", desc: "Kiểm tra khôi phục dữ liệu định kỳ", risk: "high" },
      { name: "Redundancy Architecture", nameVi: "Kiến trúc dự phòng", desc: "HA và failover cho hệ thống quan trọng", risk: "high" },
      { name: "Crisis Communication", nameVi: "Truyền thông khủng hoảng", desc: "Kế hoạch truyền thông khi sự cố lớn", risk: "medium" },
      { name: "Alternative Work Sites", nameVi: "Địa điểm làm việc thay thế", desc: "Văn phòng dự phòng và làm việc từ xa", risk: "medium" },
      { name: "Supply Chain Continuity", nameVi: "Tính liên tục chuỗi cung ứng", desc: "Kế hoạch dự phòng nhà cung cấp", risk: "medium" },
      { name: "BCP Documentation", nameVi: "Tài liệu BCP", desc: "Tài liệu hóa và cập nhật BCP thường xuyên", risk: "high" },
      { name: "BCP Exercise", nameVi: "Diễn tập BCP", desc: "Diễn tập kế hoạch kinh doanh liên tục hàng năm", risk: "medium" },
    ],
    "compliance-legal": [
      { name: "Regulatory Compliance", nameVi: "Tuân thủ quy định", desc: "Tuân thủ các quy định ngành và quốc gia", risk: "critical" },
      { name: "ISO 27001 Compliance", nameVi: "Tuân thủ ISO 27001", desc: "Chứng nhận ISO 27001 cho ISMS", risk: "high" },
      { name: "SOC 2 Compliance", nameVi: "Tuân thủ SOC 2", desc: "Báo cáo SOC 2 Type II", risk: "high" },
      { name: "GDPR Compliance", nameVi: "Tuân thủ GDPR", desc: "Tuân thủ Quy định bảo vệ dữ liệu EU", risk: "high" },
      { name: "NIST Framework", nameVi: "Khung NIST", desc: "Áp dụng NIST Cybersecurity Framework", risk: "medium" },
      { name: "PCI DSS Compliance", nameVi: "Tuân thủ PCI DSS", desc: "Bảo mật dữ liệu thẻ thanh toán", risk: "critical" },
      { name: "Legal Requirements", nameVi: "Yêu cầu pháp lý", desc: "Tuân thủ luật an toàn thông tin mạng VN", risk: "high" },
      { name: "Contractual Obligations", nameVi: "Nghĩa vụ hợp đồng", desc: "Đáp ứng cam kết bảo mật trong hợp đồng", risk: "medium" },
      { name: "Audit Management", nameVi: "Quản lý kiểm toán", desc: "Chuẩn bị và quản lý kiểm toán bảo mật", risk: "medium" },
      { name: "Evidence Collection", nameVi: "Thu thập bằng chứng", desc: "Thu thập và lưu giữ bằng chứng tuân thủ", risk: "medium" },
      { name: "Privacy Impact Assessment", nameVi: "Đánh giá tác động quyền riêng tư", desc: "PIA cho dự án xử lý dữ liệu cá nhân", risk: "high" },
      { name: "Regulatory Reporting", nameVi: "Báo cáo theo quy định", desc: "Báo cáo sự cố theo yêu cầu cơ quan chức năng", risk: "high" },
    ],
    "cloud-security": [
      { name: "Cloud Provider Assessment", nameVi: "Đánh giá nhà cung cấp đám mây", desc: "Đánh giá bảo mật AWS/Azure/GCP", risk: "high" },
      { name: "Cloud Configuration Security", nameVi: "Bảo mật cấu hình đám mây", desc: "CIS Benchmarks cho cloud resources", risk: "critical" },
      { name: "Cloud Access Management", nameVi: "Quản lý truy cập đám mây", desc: "IAM policies và least privilege trong cloud", risk: "high" },
      { name: "Cloud Data Protection", nameVi: "Bảo vệ dữ liệu đám mây", desc: "Mã hóa và DLP cho dữ liệu trên cloud", risk: "high" },
      { name: "Cloud Network Security", nameVi: "An ninh mạng đám mây", desc: "VPC, Security Groups, Network ACLs", risk: "high" },
      { name: "Cloud Monitoring", nameVi: "Giám sát đám mây", desc: "CloudTrail, CloudWatch, Azure Monitor", risk: "high" },
      { name: "Multi-Cloud Security", nameVi: "Bảo mật đa đám mây", desc: "Bảo mật nhất quán qua nhiều cloud", risk: "medium" },
      { name: "Serverless Security", nameVi: "Bảo mật serverless", desc: "Bảo mật Lambda/Functions", risk: "medium" },
      { name: "Cloud Backup", nameVi: "Sao lưu đám mây", desc: "Sao lưu dữ liệu cloud và cross-region", risk: "high" },
      { name: "Cloud Compliance", nameVi: "Tuân thủ đám mây", desc: "Tuân thủ quy định khi sử dụng cloud", risk: "high" },
      { name: "Cloud Incident Response", nameVi: "Ứng phó sự cố đám mây", desc: "Quy trình ứng phó sự cố trên cloud", risk: "medium" },
      { name: "Cloud Cost Security", nameVi: "Bảo mật chi phí đám mây", desc: "Ngăn chặn cryptojacking và cost overrun", risk: "low" },
      { name: "Container Orchestration Security", nameVi: "Bảo mật điều phối container", desc: "Kubernetes security best practices", risk: "high" },
    ],
    "mobile-security": [
      { name: "MDM Implementation", nameVi: "Triển khai MDM", desc: "Mobile Device Management cho tất cả thiết bị", risk: "high" },
      { name: "Mobile App Security", nameVi: "Bảo mật ứng dụng di động", desc: "OWASP MASVS cho ứng dụng mobile", risk: "high" },
      { name: "BYOD Policy", nameVi: "Chính sách BYOD", desc: "Quy định sử dụng thiết bị cá nhân", risk: "medium" },
      { name: "Mobile Data Encryption", nameVi: "Mã hóa dữ liệu di động", desc: "Mã hóa dữ liệu trên thiết bị di động", risk: "high" },
      { name: "Mobile Threat Defense", nameVi: "Phòng thủ mối đe dọa di động", desc: "Bảo vệ chống malware và phishing trên mobile", risk: "high" },
      { name: "App Store Security", nameVi: "Bảo mật cửa hàng ứng dụng", desc: "Chỉ cài đặt app từ store chính thức", risk: "medium" },
      { name: "Remote Wipe Capability", nameVi: "Khả năng xóa từ xa", desc: "Xóa dữ liệu từ xa khi thiết bị mất", risk: "high" },
      { name: "Mobile Network Security", nameVi: "Bảo mật mạng di động", desc: "VPN và bảo mật kết nối di động", risk: "medium" },
      { name: "Mobile Update Management", nameVi: "Quản lý cập nhật di động", desc: "Bắt buộc cập nhật OS và app mới nhất", risk: "medium" },
    ],
    "iot-security": [
      { name: "IoT Device Inventory", nameVi: "Danh mục thiết bị IoT", desc: "Theo dõi tất cả thiết bị IoT", risk: "high" },
      { name: "IoT Network Isolation", nameVi: "Cô lập mạng IoT", desc: "VLAN riêng cho thiết bị IoT", risk: "high" },
      { name: "IoT Firmware Security", nameVi: "Bảo mật firmware IoT", desc: "Cập nhật và xác thực firmware", risk: "high" },
      { name: "IoT Authentication", nameVi: "Xác thực IoT", desc: "Xác thực mạnh cho thiết bị IoT", risk: "high" },
      { name: "IoT Data Protection", nameVi: "Bảo vệ dữ liệu IoT", desc: "Mã hóa dữ liệu từ thiết bị IoT", risk: "medium" },
      { name: "IoT Default Password", nameVi: "Mật khẩu mặc định IoT", desc: "Thay đổi mật khẩu mặc định tất cả IoT", risk: "critical" },
      { name: "IoT Monitoring", nameVi: "Giám sát IoT", desc: "Giám sát hành vi bất thường thiết bị IoT", risk: "medium" },
      { name: "IoT Lifecycle Management", nameVi: "Quản lý vòng đời IoT", desc: "Quản lý từ triển khai đến ngừng sử dụng", risk: "low" },
    ],
    "crypto-management": [
      { name: "Key Generation", nameVi: "Tạo khóa", desc: "Tạo khóa theo tiêu chuẩn NIST", risk: "critical" },
      { name: "Key Storage", nameVi: "Lưu trữ khóa", desc: "HSM/KMS lưu trữ khóa an toàn", risk: "critical" },
      { name: "Key Distribution", nameVi: "Phân phối khóa", desc: "Phân phối khóa qua kênh an toàn", risk: "high" },
      { name: "Key Rotation", nameVi: "Xoay vòng khóa", desc: "Xoay vòng khóa định kỳ", risk: "high" },
      { name: "Key Revocation", nameVi: "Thu hồi khóa", desc: "Thu hồi khóa khi bị xâm phạm", risk: "high" },
      { name: "Certificate Management", nameVi: "Quản lý chứng thư số", desc: "Quản lý vòng đời chứng chỉ SSL/TLS", risk: "high" },
      { name: "Algorithm Standards", nameVi: "Tiêu chuẩn thuật toán", desc: "Sử dụng thuật toán mã hóa chuẩn", risk: "high" },
      { name: "Digital Signatures", nameVi: "Chữ ký số", desc: "Xác thực và toàn vẹn bằng chữ ký số", risk: "medium" },
      { name: "Crypto Agility", nameVi: "Linh hoạt mã hóa", desc: "Sẵn sàng chuyển đổi thuật toán", risk: "medium" },
      { name: "Random Number Generation", nameVi: "Tạo số ngẫu nhiên", desc: "TRNG/CSPRNG cho mật mã", risk: "high" },
      { name: "Post-Quantum Readiness", nameVi: "Sẵn sàng hậu lượng tử", desc: "Chuẩn bị cho mật mã hậu lượng tử", risk: "medium" },
    ],
    "vendor-security": [
      { name: "Vendor Risk Assessment", nameVi: "Đánh giá rủi ro nhà cung cấp", desc: "Đánh giá bảo mật nhà cung cấp", risk: "high" },
      { name: "Vendor Contracts", nameVi: "Hợp đồng nhà cung cấp", desc: "Điều khoản bảo mật trong hợp đồng", risk: "high" },
      { name: "Vendor Access Control", nameVi: "Kiểm soát truy cập nhà cung cấp", desc: "Giám sát truy cập của nhà cung cấp", risk: "high" },
      { name: "Vendor Monitoring", nameVi: "Giám sát nhà cung cấp", desc: "Theo dõi tuân thủ bảo mật định kỳ", risk: "medium" },
      { name: "Third-Party Auditing", nameVi: "Kiểm toán bên thứ ba", desc: "Yêu cầu SOC 2/ISO từ nhà cung cấp", risk: "medium" },
      { name: "Vendor Incident Response", nameVi: "Ứng phó sự cố nhà cung cấp", desc: "Quy trình khi nhà cung cấp có sự cố", risk: "high" },
      { name: "Supply Chain Security", nameVi: "An ninh chuỗi cung ứng", desc: "Bảo mật toàn bộ chuỗi cung ứng", risk: "high" },
      { name: "Vendor Termination", nameVi: "Chấm dứt nhà cung cấp", desc: "Quy trình khi chấm dứt hợp đồng", risk: "medium" },
      { name: "SaaS Security Assessment", nameVi: "Đánh giá bảo mật SaaS", desc: "Đánh giá bảo mật dịch vụ SaaS", risk: "high" },
      { name: "Vendor Inventory", nameVi: "Danh mục nhà cung cấp", desc: "Danh sách đầy đủ nhà cung cấp và dịch vụ", risk: "medium" },
    ],
    "monitoring-audit": [
      { name: "SIEM Implementation", nameVi: "Triển khai SIEM", desc: "Hệ thống quản lý sự kiện bảo mật", risk: "high" },
      { name: "Log Management", nameVi: "Quản lý log", desc: "Thu thập và lưu trữ log tập trung", risk: "high" },
      { name: "Real-time Monitoring", nameVi: "Giám sát thời gian thực", desc: "Giám sát bảo mật 24/7", risk: "high" },
      { name: "Anomaly Detection", nameVi: "Phát hiện bất thường", desc: "ML/AI phát hiện hành vi bất thường", risk: "medium" },
      { name: "Audit Trail", nameVi: "Dấu vết kiểm toán", desc: "Ghi lại đầy đủ hoạt động hệ thống", risk: "high" },
      { name: "Compliance Monitoring", nameVi: "Giám sát tuân thủ", desc: "Giám sát tuân thủ chính sách liên tục", risk: "medium" },
      { name: "Performance Monitoring", nameVi: "Giám sát hiệu năng", desc: "Theo dõi hiệu năng hệ thống", risk: "low" },
      { name: "Security Metrics", nameVi: "Chỉ số bảo mật", desc: "KPI và dashboard bảo mật", risk: "medium" },
      { name: "User Activity Monitoring", nameVi: "Giám sát hoạt động người dùng", desc: "Theo dõi hành vi người dùng đặc quyền", risk: "high" },
      { name: "Network Forensics", nameVi: "Điều tra mạng", desc: "Thu thập và phân tích dữ liệu mạng", risk: "medium" },
      { name: "Alert Management", nameVi: "Quản lý cảnh báo", desc: "Phân loại và xử lý cảnh báo bảo mật", risk: "high" },
      { name: "Audit Reporting", nameVi: "Báo cáo kiểm toán", desc: "Báo cáo kiểm toán bảo mật định kỳ", risk: "medium" },
    ],
    "security-governance": [
      { name: "Security Strategy", nameVi: "Chiến lược bảo mật", desc: "Chiến lược bảo mật phù hợp mục tiêu kinh doanh", risk: "high" },
      { name: "Security Policies", nameVi: "Chính sách bảo mật", desc: "Bộ chính sách bảo mật đầy đủ", risk: "high" },
      { name: "Security Organization", nameVi: "Tổ chức bảo mật", desc: "Cơ cấu tổ chức bảo mật rõ ràng", risk: "high" },
      { name: "Security Budget", nameVi: "Ngân sách bảo mật", desc: "Ngân sách bảo mật đầy đủ và hiệu quả", risk: "medium" },
      { name: "Risk Management", nameVi: "Quản lý rủi ro", desc: "Quy trình đánh giá và xử lý rủi ro", risk: "critical" },
      { name: "Security Standards", nameVi: "Tiêu chuẩn bảo mật", desc: "Áp dụng tiêu chuẩn bảo mật quốc tế", risk: "high" },
      { name: "Security Architecture", nameVi: "Kiến trúc bảo mật", desc: "Thiết kế kiến trúc bảo mật defense-in-depth", risk: "high" },
      { name: "Security KPIs", nameVi: "Chỉ số KPI bảo mật", desc: "Đo lường hiệu quả bảo mật", risk: "medium" },
      { name: "Security Reporting", nameVi: "Báo cáo bảo mật", desc: "Báo cáo cho lãnh đạo cấp cao", risk: "medium" },
      { name: "Security Maturity Assessment", nameVi: "Đánh giá độ trưởng thành", desc: "Đánh giá mức độ trưởng thành bảo mật", risk: "medium" },
      { name: "Security Program Management", nameVi: "Quản lý chương trình bảo mật", desc: "Quản lý chương trình bảo mật tổng thể", risk: "high" },
      { name: "Board Communication", nameVi: "Truyền thông hội đồng", desc: "Báo cáo bảo mật cho hội đồng quản trị", risk: "medium" },
      { name: "Security Culture Program", nameVi: "Chương trình văn hóa bảo mật", desc: "Xây dựng văn hóa bảo mật toàn tổ chức", risk: "medium" },
    ],
  };

  let counter = 1;
  for (const domain of DOMAINS) {
    const domainCriteriaList = domainCriteria[domain.id] || [];
    domainCriteriaList.forEach((c, idx) => {
      criteria.push({
        id: `CR-${String(counter).padStart(3, "0")}`,
        domainId: domain.id,
        code: `${domain.id.toUpperCase().replace(/-/g, "-")}-${String(idx + 1).padStart(2, "0")}`,
        name: c.name,
        nameVi: c.nameVi,
        description: c.desc,
        riskLevel: c.risk,
        iso27001Control: isoControls[counter % isoControls.length],
        soc2Criteria: soc2Criteria[counter % soc2Criteria.length],
        weight: c.risk === "critical" ? 5 : c.risk === "high" ? 4 : c.risk === "medium" ? 3 : c.risk === "low" ? 2 : 1,
      });
      counter++;
    });
  }

  return criteria;
}

export const CRITERIA: SecurityCriterion[] = generateCriteria();
